#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-swagger-core
Version  : 1.5.4
Release  : 2
URL      : https://github.com/swagger-api/swagger-core/archive/v1.5.4.tar.gz
Source0  : https://github.com/swagger-api/swagger-core/archive/v1.5.4.tar.gz
Source1  : https://repo1.maven.org/maven2/io/swagger/swagger-annotations/1.5.4/swagger-annotations-1.5.4.jar
Source2  : https://repo1.maven.org/maven2/io/swagger/swagger-annotations/1.5.4/swagger-annotations-1.5.4.pom
Source3  : https://repo1.maven.org/maven2/io/swagger/swagger-project/1.5.4/swagger-project-1.5.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-swagger-core-data = %{version}-%{release}

%description
# Swagger Core library
[![Build Status](https://travis-ci.org/swagger-api/swagger-core.svg?branch=master)](https://travis-ci.org/swagger-api/swagger-core)
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/io.swagger/swagger-project/badge.svg?style=plastic)](https://maven-badges.herokuapp.com/maven-central/io.swagger/swagger-project)

%package data
Summary: data components for the mvn-swagger-core package.
Group: Data

%description data
data components for the mvn-swagger-core package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/swagger/swagger-annotations/1.5.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/swagger/swagger-annotations/1.5.4/swagger-annotations-1.5.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/swagger/swagger-annotations/1.5.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/swagger/swagger-annotations/1.5.4/swagger-annotations-1.5.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/swagger/swagger-project/1.5.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/io/swagger/swagger-project/1.5.4/swagger-project-1.5.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/swagger/swagger-annotations/1.5.4/swagger-annotations-1.5.4.jar
/usr/share/java/.m2/repository/io/swagger/swagger-annotations/1.5.4/swagger-annotations-1.5.4.pom
/usr/share/java/.m2/repository/io/swagger/swagger-project/1.5.4/swagger-project-1.5.4.pom
